### ISSUE TITLE
The project depends on the archive repository `avto-dev/open-rpc-docs-builder-docker`

### ISSUE THREAD

**Issue by gomzyakov** [shirokovnv/json-rpc-starter#1]
Your use https://github.com/avto-dev/open-rpc-docs-builder-docker in `docker-compose.yml`

This is a problem because the dependency will no longer develop.

**Comment by shirokovnv** [comment]
Yes, indeed. 
Need more time to investigate existence of similar dependencies or just implement it. 
The milestone is set.

**Comment by shirokovnv** [comment]
Removed avto-dev open rpc docs builder dependency in 205c2a340a2cd502f2505517c3d7751407eec1a6

**Comment by gomzyakov** [comment]
Thank! 🤝
