### ISSUE TITLE
Please lint the `openrpc.json` file on CI

### ISSUE THREAD

**Issue by gomzyakov** [shirokovnv/json-rpc-starter#4]

**Comment by shirokovnv** [comment]
Thanks for opening issue :) 
Added linting https://github.com/shirokovnv/json-rpc-starter/commit/c34b5c794a5bb2d1bce374936261445c94c862af and validation https://github.com/shirokovnv/json-rpc-starter/commit/52eaa205e440ce30438ca8daa80d32ddd2353d0a

**Comment by gomzyakov** [comment]
Looks good) Thanks!

P.S. Commit https://github.com/shirokovnv/json-rpc-starter/commit/c34b5c794a5bb2d1bce374936261445c94c862af have a some warnings "No newline at the end of file"
